name: sanmill
description: Sanmill is a open-source, powerful UCI-like Nine Men's Morris (and its variants) program.
publish_to: none
version: 2.0.0+2627


environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.1.1
  catcher: ^0.6.9
  collection: ^1.15.0
  copy_with_extension: ^4.0.0
  cupertino_icons: ^1.0.4
  device_info_plus_platform_interface: ^2.3.0
  double_back_to_close_app: ^2.1.0
  feedback: ^2.4.1
  fluentui_system_icons: ^1.1.161
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_email_sender: ^5.1.0
  flutter_localizations:
    sdk: flutter

  # local database
  hive: ^2.0.6
  hive_flutter: ^1.1.0

  #localization
  intl: ^0.17.0

  json_annotation: ^4.4.0
  logger: ^1.1.0
  package_info_plus: ^1.4.0
  path_provider: ^2.0.9
  soundpool: ^2.3.0
  url_launcher: ^6.0.20
  uuid: ^3.0.6
  #pref: ^2.3.0
  #screen_recorder: ^0.0.2

dev_dependencies:
  build_runner: ^2.1.7
  copy_with_extension_gen: ^4.0.1
  flutter_driver:
    sdk: flutter

  flutter_gen_runner: ^4.1.6
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.2

  json_serializable: ^6.1.5
  lint: ^1.8.2
  mockito: any
  msix: ^3.3.1
  source_gen: ^1.2.1
  test: any

flutter_gen:
  output: lib/generated/assets/

flutter:
  generate: false
  uses-material-design: true

  assets:
    - assets/files/git-branch.txt
    - assets/files/git-revision.txt
    - assets/licenses/GPL-3.0.txt
    - assets/audios/draw.mp3
    - assets/audios/fly.mp3
    - assets/audios/go.mp3
    - assets/audios/illegal.mp3
    - assets/audios/lose.mp3
    - assets/audios/mill.mp3
    - assets/audios/place.mp3
    - assets/audios/remove.mp3
    - assets/audios/select.mp3
    - assets/audios/win.mp3

flutter_intl:
  enabled: true

msix_config:
  display_name: Sanmill
  publisher_display_name: Calcitem Studio
  identity_name: 25314CalcitemStudio.Sanmill
  publisher: CN=3413C020-B420-4E0A-8687-A2C35E878F3A
  capabilities: ""
  store: true
